### ISSUE TITLE
Stack Multi-select Labels

### ISSUE THREAD

**Issue by williamcaruso** [ibraheem-ghazi/four-boot#4]
Is there any way to prevent selected labels from appearing on one line?

Let's say, after a certain width is reached, the labels can start a new line?

**Comment by ibraheem-ghazi** [comment]
try this css code:
```css
[data-four-boot-item]{
    max-width: 200px;
    white-space: normal;
}
```
take a look at this example:
https://codepen.io/ibraheemalnabriss/pen/ajOKEv
